# Generated by Django 2.1.3 on 2019-04-21 17:27

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.TextField()),
                ('approved_comment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(default='')),
                ('photo', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/photos'), upload_to='')),
                ('content', models.TextField(default='')),
                ('promo_code', models.CharField(default='', max_length=50, null=True)),
                ('statut_promo', models.BooleanField(default=False)),
                ('price_before', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_after', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('in_shop', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='CA', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fol_dea_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fol_deals', to='bestdeal.Deal')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fol_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lik_com_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lik_comments', to='bestdeal.Comment')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lik_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/photos_marques'), upload_to='')),
                ('link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sco_dea_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sco_deals', to='bestdeal.Deal')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sco_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/photos_tag'), upload_to='')),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='dea_mar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dea_marques', to='bestdeal.Marque'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tag_set',
            field=models.ManyToManyField(related_name='dea_tags', to='bestdeal.Tag'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dea_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_dea_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_deals', to='bestdeal.Deal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
