# Generated by Django 2.1.3 on 2019-04-21 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id_guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
