# Generated by Django 2.1.3 on 2019-05-06 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0002_auto_20190421_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MinValueValidator(1)]),
        ),
    ]
