# Generated by Django 2.1.3 on 2018-11-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0002_deal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
