# Generated by Django 2.2.1 on 2019-05-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0004_abusereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='abu_com_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_comment', to='bestdeal.Comment'),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='abu_dea_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_deal', to='bestdeal.Deal'),
        ),
    ]
