# Generated by Django 2.2.1 on 2019-05-22 23:34

import bestdeal.api.deal.models
import bestdeal.api.brand.models
import bestdeal.api.tag.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.TextField()),
                ('approved_comment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(default='')),
                ('photo', models.ImageField(null=True, upload_to=bestdeal.api.deal.models.deal_image_file_path)),
                ('content', models.TextField(default='')),
                ('promo_code', models.CharField(default='', max_length=50, null=True)),
                ('statut_promo', models.BooleanField(default=False)),
                ('price_before', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_after', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('in_shop', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='CA', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to=bestdeal.api.tag.models.tag_image_file_path)),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sco_dea_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sco_deals', to='bestdeal.Deal')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sco_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to=bestdeal.api.brand.models.brand_image_file_path)),
                ('link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lik_com_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lik_comments', to='bestdeal.Comment')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lik_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fol_dea_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_deals', to='bestdeal.Deal')),
                ('user_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='brand_fk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dea_brands', to='bestdeal.Brand'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tag_set',
            field=models.ManyToManyField(related_name='dea_tags', to='bestdeal.Tag'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dea_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_dea_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_deals', to='bestdeal.Deal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url_deal', models.URLField(default='')),
                ('text', models.TextField()),
                ('spam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abu_com_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_comment', to='bestdeal.Comment')),
                ('abu_dea_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_deal', to='bestdeal.Deal')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
